"""Render BACKEND_CAPABILITY_MATRIX.md from the search-space registry.

The matrix is generated, never hand-maintained. A hand-written capability table
drifts from the code the moment someone changes a validation branch, and a
drifted capability table is worse than none: it authorises a search over a knob
that no longer exists.
"""
import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from turbo.optimizer import lane_c, search_space as space

HEADER = ('control', 'llama_cpp_cpu', 'llama_cpp_htp', 'qairt_npu', 'officially supported',
          'actually wired', 'requires reload', 'qualified search allowed', 'diagnostic only',
          'evidence / code location')


def _cell(name, backend):
    spec = space.parameter(name)
    if spec['support_status'] == space.SUPPORTED and backend in spec['backends']:
        allowed = spec['allowed_values']
        return 'yes (' + ', '.join(repr(v) for v in allowed) + ')' if allowed else 'yes'
    if backend in spec['backends']:
        return 'declared, status ' + spec['support_status']
    return 'no'


def rows():
    for name in space.PARAMETERS:
        spec = space.PARAMETERS[name]
        supported = spec['support_status'] == space.SUPPORTED
        qualified = any(space.admissible_for_qualified_search(name, b) for b in space.BACKENDS)
        diagnostic = spec['support_status'] in (space.DIAGNOSTIC_ONLY,
                                                space.REQUIRES_PROTOCOL_EXTENSION)
        yield ('`' + name + '`',
               _cell(name, 'llama_cpp_cpu'), _cell(name, 'llama_cpp_htp'), _cell(name, 'qairt_npu'),
               'yes' if supported else spec['support_status'],
               spec['wiring'],
               'yes' if spec['requires_restart'] else 'no',
               'yes' if qualified else 'no',
               'yes' if diagnostic else 'no',
               spec['evidence'])


def render():
    lines = ['# Backend capability matrix', '',
             'Generated by `scripts/render_backend_capability_matrix.py` from',
             '`turbo/optimizer/search_space.py`. Do not edit by hand: regenerate it.',
             'This table is TurboLab\'s source of truth for what may be searched.', '',
             '"Officially supported" means the frozen runner accepts the key and the native layer',
             'does not reject it for that backend. "Actually wired" is a separate question: a',
             'control can exist as a struct field and still have no path from configuration to',
             'the runtime, which is exactly the case for the QAIRT sampler fields.', '',
             '| ' + ' | '.join(HEADER) + ' |',
             '|' + '|'.join(['---'] * len(HEADER)) + '|']
    for row in rows():
        lines.append('| ' + ' | '.join(str(cell).replace('|', '\\|') for cell in row) + ' |')
    lines += ['',
              '## Single-variable treatment ceiling per backend', '',
              'One candidate changes exactly one field, because `turbo/campaign_plan.py` refuses a',
              'treatment that differs from its control in more than one place. The ceiling below is',
              'therefore a sum of enumeration sizes, not a Cartesian product.', '',
              '| backend | supported controls | maximum single-variable treatments |',
              '|---|---|---:|']
    for backend in space.BACKENDS:
        names = space.supported_parameters(backend)
        lines.append('| `' + backend + '` | ' + ', '.join('`' + n + '`' for n in names)
                     + ' | ' + str(space.space_size(backend)) + ' |')
    lines += ['',
              'The QAIRT figure is small and that is a finding, not a defect of the search engine.',
              'High-volume search is genuinely available on the llama.cpp backends; on QAIRT the',
              'honest answer is that the current contract exposes two controls.', '',
              '## Lane C register', '',
              'Controls and mechanisms the current contract cannot express. None of these may',
              'reach a qualified experiment. They are recorded so the questions survive.', '',
              '| item | missing capability | smallest safe extension | benchmark semantics | priority |',
              '|---|---|---|---|---|']
    for key, record in lane_c.RESEARCH_ITEMS.items():
        lines.append('| `' + key + '` | ' + record['missing_capability'] + ' | '
                     + record['smallest_safe_extension'] + ' | ' + record['benchmark_semantics']
                     + ' | ' + record['priority'] + ' |')
    lines += ['',
              'Full detail, including the files each item would touch and how it must be validated,',
              'lives in `turbo/optimizer/lane_c.py`.', '']
    return '\n'.join(lines)


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--output', type=Path, default=ROOT / 'BACKEND_CAPABILITY_MATRIX.md')
    p.add_argument('--check', action='store_true',
                   help='Exit nonzero when the file on disk differs from the generated matrix')
    args = p.parse_args(argv)
    text = render()
    if args.check:
        current = args.output.read_text(encoding='utf-8') if args.output.exists() else None
        if current != text:
            print('BACKEND_CAPABILITY_MATRIX.md is stale; regenerate it')
            return 1
        return 0
    args.output.write_text(text, encoding='utf-8', newline='\n')
    print('Wrote ' + str(args.output))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
